/**/controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controllers:
      type: position_controllers/JointGroupPositionController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


/**/position_controllers:
  ros__parameters:
    joints:
      - base
      - shoulder
      - elbow
      - wrist1
      - wrist2
      - wrist3


/**/joint_trajectory_controller:
  ros__parameters:
    joints:
      - base
      - shoulder
      - elbow
      - wrist1
      - wrist2
      - wrist3

    command_interfaces:
      - position

    state_interfaces:
      - position

    # [추가] 궤적 보간 방법 설정
    interpolation_method: splines # 선형 대신 스플라인 사용하여 부드럽게 연결

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true

    # [추가] 제약 조건 최적화
    # constraints:
    #   stopped_velocity_tolerance: 0.02 # 정지 판단 속도 완화
    #   goal_time: 0.6 # 목표 도달 시간 여유 부여
    #   base: { trajectory: 0.1, goal: 0.05 }
    #   shoulder: { trajectory: 0.1, goal: 0.05 }
    #   elbow: { trajectory: 0.1, goal: 0.05 }
    #   wrist1: { trajectory: 0.1, goal: 0.05 }
    #   wrist2: { trajectory: 0.1, goal: 0.05 }
    #   wrist3: { trajectory: 0.1, goal: 0.05 }